### ISSUE TITLE
Phantomjs timing out with Jasmine.

### ISSUE THREAD

**Issue by vytch** [jasmine-contrib/grunt-jasmine-runner#15]
Hi

I have been trying grunt for a couple of weeks and I am very excited about that project.
However it looks like I am having issues using jasmine with phantomjs.

Here is the error message I have each time the unit test task is triggered:
PhantomJS timed out, possibly due to an unfinished async spec. Use --force to continue.

It looks like it happens each time my network is behind a proxy.

Is there any way I can solve that?

Thanks.

**Comment by jsoverson** [comment]
Are you using the most up-to-date version? That error was something I noticed before but has been fixed. If you are, then try running grunt with the -vd flags to get more output.

I'd be surprised if it was happening behind a proxy. Is your proxy configured to serve localhost (127.0.0.1)?

**Comment by jsoverson** [comment]
Future development of this task will be done in [grunt-contrib-jasmine](https://github.com/gruntjs/grunt-contrib-jasmine). Closing because of the change and lack of response.

**Comment by vytch** [comment]
Hi

The issue is still happening.
From the documentation, I'd assume that I could just use the phantomjs settings:

```
phantomjs:{
  'proxy':'IP:80',
  'proxy-type':'http'
}
```
